### GET RIDER 
GET http://localhost:3001

### POST RIDER 
POST http://localhost:3001/rider
Content-Type: application/json

{
  "lat":122.111,
   "lng":34.222,
   "riderId":"rider123s3"

}

### GET RIDERS
GET http://localhost:3001/rider